version: "3"
services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - ./docker/db/data:/var/lib/postgres/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"

  web:
    container_name: web
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    volumes:
      - .:/var/www
      - ./bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    links:
      - postgres
    tty: true
    stdin_open: true
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
