default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER", "root") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "root") %>
  host: <%= ENV.fetch("POSTGRES_HOST", "postgres") %>

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  adapter: postgresql
  host: Rails.application.credentials.db[:host]
  port: Rails.application.credentials.db[:port]
  encoding: utf8
  database: Rails.application.credentials.db[:database]
  username: Rails.application.credentials.db[:user]
  password: Rails.application.credentials.db[:password]
  pool: 5
  timeout: 5000
